admin:
  secret-key: ${ADMIN_SECRET_KEY:local-secret-key}

server:
  forward-headers-strategy: native

spring:
  profiles:
    active: local # 💡 인텔리제이에서 켤 때는 무조건 local로 작동!

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: my-community-image-bucket-123
        folder: ${S3_FOLDER:local}
      region:
        static: ap-northeast-2

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100 # N+1 방지!

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # 발송할 본인의 구글 이메일 (예: test@gmail.com)
    password: ${MAIL_PASSWORD} # 구글 계정 '앱 비밀번호' (기존 비밀번호 아님!)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ==========================================
# ⚙️ 커뮤니티 서비스 자체 정책 설정값 (Custom Properties)
# ==========================================
app:
  policy:
    post-retention-days: 30
    view-count-ttl-hours: 24
  # ==========================================
  # ⏰ 스케줄러 실행 시간 설정
  # ==========================================
  scheduler:
    cleanup-cron: "0 0 3 * * ?" # 매일 새벽 3시 실행
#    cleanup-cron: "0/10 * * * * ?" # Test용 10초